version: '3.8'

services:
  frontend:
    image: hunghx12/comp90024-frontend
    hostname: frontend
    command: gunicorn --bind 0.0.0.0:5000 wsgi:application
    environment:
      - COUCHDB_DATABASE=http://user:password@172.26.134.34:5984
      - COUCHDB_DATABASE_NAME=new_tweets
      - COUCHDB_USERNAME=user
      - COUCHDB_HISTORICAL_TWEETS_TABLE_NAME=historical_tweets
  nginx:
    image: nginx:latest
    volumes:
      - /etc/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8088:80
    depends_on:
      - frontend
  harvester-melb:
    image: hunghx12/comp90024-harvester
    command: python main.py --credentials-id 0 --couchdb-host 172.26.134.34:5984 --couchdb-username user --city melbourne --mode stream --debug
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  harvester-melb-transport:
    image: hunghx12/comp90024-harvester
    command: python main.py --credentials-id 1 --couchdb-host 172.26.134.34:5984 --couchdb-username user --city melbourne --topic transport --mode stream --debug
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure