---
- name: Create CouchDB directory
  become: yes
  ansible.builtin.file:
    path: "{{ couchdb_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Creating CouchDB Container
  become: yes
  docker_container:
    name: couchdb_container
    image: couchdb:3.2
    ports:
      - "5984:5984"
      - "4369:4369"
      # - "15984:15984"
      # - "25984:25984"
      - "9100-9200:9100-9200"
      - "80:80"
    volumes:
      - "{{ couchdb_dir }}:/opt/couchdb/data"
    env:
      COUCHDB_USER: "{{ database_user }}"
      COUCHDB_PASSWORD: "{{ database_password }}"
      COUCHDB_SECRET: "{{ database_cookie }}"
      NODENAME: "{{ ansible_host }}"
      ERFLAGS: "-setcookie {{ database_cookie }} -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200"
