---
- name: Add Workers to the Swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars[item]['worker_token']['stdout'] }}"
    remote_addrs: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}:2377"
  with_items: "{{ groups.swarm_managers[0] }}"
  tags: swarm