---
- name: Check if Swarm has already been Initialized
  become: yes
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  become: yes
  docker_swarm:
    state: present
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Create token for managers
  shell: docker swarm join-token -q manager
  register: manager_token
  tags: swarm

- name: Create token for workers
  shell: docker swarm join-token -q worker
  register: worker_token
  tags: swarm