# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: project-key
instance_flavor: uom.mse.2c9g
cloud_network: qh2-uom

# Volume
volumes:
  - vol_name: web-application-vol-1-1
    vol_size: 10
  - vol_name: web-application-vol-1-2
    vol_size: 10

# Security group
security_groups:
  - name: ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: nginx
    description: "Security group for HTTP/nginx"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: web-application
    volumes: ['web-application-vol-1-1', 'web-application-vol-1-2']
