---
- name: Create web app file directory
  become: yes
  ansible.builtin.file:
    path: "{{ web_app_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Copy files to remote
  become: yes
  copy:
    src: "{{ playbook_dir }}/../web_application/"
    dest: "{{ web_app_dir }}/"
    force: true

- name: Sanity check that file(s) exist
  stat:
    path: "{{ web_app_dir }}/README.md"
  register: splunkresult
  tags:
    - always

- name: Configure compose
  become: yes
  ansible.builtin.template:
    src: "docker-compose.prod.yml"
    dest: "{{ web_app_dir }}/docker-compose.prod.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# - name: Run docker compose
#   become: yes
#   community.docker.docker_compose:
#     project_src: "{{ web_app_dir }}"
#     files:
#       - "docker-compose.prod.yml"
#     pull: yes
#     state: present
#     remove_orphans: yes
#     recreate: always
#     debug: true

- name: Start and build docker
  become: yes
  command: "docker-compose -f {{ web_app_dir }}/docker-compose.prod.yml down -v"
  command: "docker-compose -f {{ web_app_dir }}/docker-compose.prod.yml up -d --build"

- name: Get infos on container
  become: yes
  docker_container_info:
    name: web_web_1
  register: result

- name: Does flask container exist?
  debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Print the status of the container
  debug:
    msg: "The container status is {{ result.container['State']['Status'] }}"
  when: result.exists