version: '3.8'

services:
  web:
    build: ./services/web/flask
    command: python wsgi.py
    volumes:
      - ./services/web/flask:/usr/src/app/
    ports:
      - 5000:5000
    environment:
      - COUCHDB_DATABASE=http://user:password@172.26.134.34:5984
      - COUCHDB_DATABASE_NAME=new_tweets
      - COUCHDB_USERNAME=user
      - COUCHDB_HISTORICAL_TWEETS_TABLE_NAME=historical_tweets