version: '3.8'

services:
  web:
    build: ./services/web/flask
    command: python flask/wsgi.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev