---
- name: Initialize Docker Swarm cluster
  hosts: swarm_managers[0]
  roles:
    - docker-swarm-init

- name: Add managers to cluster
  gather_facts: yes
  hosts: swarm_managers[1:9999]
  roles:
    - add-managers

- name: Add workers to cluster
  gather_facts: yes
  hosts: swarm_workers
  roles:
    - add-workers

- name: Deploy configuration files
  hosts: nodes
  roles:
    - copy-configuration

- name: Deploy service stack
  hosts: swarm_managers[0]
  roles:
    - stack-deploy