# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: project-key
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: web-vol-1-1
    vol_size: 10
  - vol_name: web-vol-2-1
    vol_size: 10
  - vol_name: db-vol-1-1
    vol_size: 50
  - vol_name: db-vol-2-1
    vol_size: 50

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb1
    description: "Security group for CouchDB Master Node"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb2
    description: "Security group for CouchDB Worker Node"
    protocol: tcp
    port_range_min: 5986
    port_range_max: 5986
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb3
    description: "Security group for CouchDB Worker Node"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb4
    description: "Security group for CouchDB Worker Node"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  
# Instance
instances:
  - name: Instance-1
    volumes: ['web-vol-1-1', 'db-vol-1-1']
  - name: Instance-2
    volumes: ['web-vol-2-1', 'db-vol-2-1']