version: '3.8'

services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./services/web/flask
    command: gunicorn --bind 0.0.0.0:5000 wsgi:application
    # volumes:
    #   - ./services/web/:/usr/src/app/
    # ports:
    #   - 5000:5000
    expose:
      - 5000
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web