version: '3.8'

services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./services/web/flask
    command: gunicorn --bind 0.0.0.0:5000 wsgi:application
    # volumes:
    #   - ./services/web/:/usr/src/app/
    # ports:
    #   - 5000:5000
    expose:
      - 5000
    environment:
      - COUCHDB_DATABASE=http://admin:password@172.26.129.203:5984
      - COUCHDB_DATABASE_NAME=test
      - COUCHDB_USERNAME=admin
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web